version: "3"
services:
  envoy:
    image: envoyproxy/envoy:dev-4168a90c65e1022073d154eb6ad24552d2cd9f4b
    ports:
      - "9901:9901"
      - "8080:8080"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml